export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    PROFILE: '/auth/profile',
    CHANGE_PASSWORD: '/auth/change-password',
  },
  DASHBOARD: {
    SUMMARY: '/dashboard/summary',
    SALES_CHART: '/dashboard/sales-chart',
    PURCHASE_CHART: '/dashboard/purchase-chart',
    TOP_PRODUCTS: '/dashboard/top-products',
    LOW_STOCK: '/dashboard/low-stock',
    ACTIVITIES: '/dashboard/activities',
  },
  SETTINGS: {
    COMPANY: '/settings/company',
    COA: '/settings/coa',
    COA_DETAIL: (id) => `/settings/coa/${id}`,
    ROLES: '/settings/roles',
    ROLE_DETAIL: (id) => `/settings/roles/${id}`,
    PERMISSIONS: '/settings/permissions',
    ADMINS: '/settings/admins',
    ADMIN_DETAIL: (id) => `/settings/admins/${id}`,
  },
  MASTER: {
    EMPLOYEES: '/master/employees',
    EMPLOYEE_DETAIL: (id) => `/master/employees/${id}`,
    CUSTOMERS: '/master/customers',
    CUSTOMER_DETAIL: (id) => `/master/customers/${id}`,
    SUPPLIERS: '/master/suppliers',
    SUPPLIER_DETAIL: (id) => `/master/suppliers/${id}`,
    PRODUCTS: '/master/products',
    PRODUCT_DETAIL: (id) => `/master/products/${id}`,
    PRODUCT_STOCK: (id) => `/master/products/${id}/stock`,
    WAREHOUSES: '/master/warehouses',
    CASH_BANK: '/master/cash-bank-accounts',
    DEPARTMENTS: '/master/departments',
    STOCKS: '/master/stocks',
  },
  PURCHASE: {
    DOWN_PAYMENTS: '/purchase/down-payments',
    DOWN_PAYMENT_POST: (id) => `/purchase/down-payments/${id}/post`,
    INVOICES: '/purchase/invoices',
    INVOICE_DETAIL: (id) => `/purchase/invoices/${id}`,
    INVOICE_POST: (id) => `/purchase/invoices/${id}/post`,
    PAYMENTS: '/purchase/payments',
    REPORTS: '/purchase/reports',
  },
  SALES: {
    DOWN_PAYMENTS: '/sales/down-payments',
    DOWN_PAYMENT_POST: (id) => `/sales/down-payments/${id}/post`,
    INVOICES: '/sales/invoices',
    INVOICE_DETAIL: (id) => `/sales/invoices/${id}`,
    INVOICE_POST: (id) => `/sales/invoices/${id}/post`,
    RECEIPTS: '/sales/receipts',
    REPORTS: '/sales/reports',
  },
  INVENTORY: {
    GOODS_RECEIPTS: '/inventory/goods-receipts',
    GOODS_RECEIPTS_EXPORT: '/inventory/goods-receipts/export',
    GOODS_ISSUES: '/inventory/goods-issues',
    STOCK_OPNAMES: '/inventory/stock-opnames',
    STOCK_OPNAME_DETAIL: (id) => `/inventory/stock-opnames/${id}`,
    STOCK_OPNAME_COMPLETE: (id) => `/inventory/stock-opnames/${id}/complete`,
    STOCK_ADJUSTMENTS: '/inventory/stock-adjustments',
    STOCK_ADJUSTMENT_APPROVE: (id) => `/inventory/stock-adjustments/${id}/approve`,
    STOCK_MOVEMENTS: '/inventory/stock-movements',
    STOCKS: '/inventory/stocks',
  },
  CASH: {
    RECEIPTS: '/cash/receipts',
    PAYMENTS: '/cash/payments',
    PAYMENT_DETAIL: (id) => `/cash/payments/${id}`,
    TRANSFERS: '/cash/transfers',
  },
  HRD: {
    ADVANCES: '/hrd/advances',
    ADVANCE_APPROVE: (id) => `/hrd/advances/${id}/approve`,
    ADVANCE_REJECT: (id) => `/hrd/advances/${id}/reject`,
    ADVANCE_DISBURSE: (id) => `/hrd/advances/${id}/disburse`,
    ADVANCE_PAYMENTS: (id) => `/hrd/advances/${id}/payments`,
    REPORTS: '/hrd/advances/reports',
    KASBON_ROKOK: {
      ITEMS: '/hrd/kasbon-rokok/items',
      ITEM_DETAIL: (id) => `/hrd/kasbon-rokok/items/${id}`,
      TRANSACTIONS: '/hrd/kasbon-rokok/transactions',
      REPORTS: '/hrd/kasbon-rokok/reports',
    },
  },
  ACCOUNTING: {
    JOURNALS: '/accounting/journals',
    JOURNAL_DETAIL: (id) => `/accounting/journals/${id}`,
    NOTIFICATIONS: '/accounting/notifications',
    NOTIFICATION_READ: (id) => `/accounting/notifications/${id}/read`,
    AUDIT_LOGS: '/accounting/audit-logs',
  },
};
